A-785: Update dependencies on decco and bazel-deps (#12)
* A-785: Update dependencies on decco and bazel-deps

* A-785: Remove double dependency on decco and keep the newest one

diff --git a/deps b/deps
--- a/deps
+++ b/deps
@@ -3,8 +3,8 @@
 ROOT=`pwd`
 
 BAZEL_DEPS_REPO="https://github.com/input-output-hk/bazel-deps.git"
-BAZEL_DEPS_COMMIT="b9baec69bdbaae53743a7c0b69828a9c66f6a624"
-IDENTIFIER="$BAZEL_DEPS_REPO|$BAZEL_DEPS_COMMIT"
+BAZEL_DEPS_TAG="latest"
+IDENTIFIER="$BAZEL_DEPS_REPO|$BAZEL_DEPS_TAG"
 
 BAZEL_DEPS="/tmp/$(echo "$IDENTIFIER" | sha256sum | awk '{ print $1 }')/.bazel-deps/"
 
@@ -24,7 +24,7 @@ if [ -e $BAZEL_DEPS ]; then
 else
     git clone "$BAZEL_DEPS_REPO" "$BAZEL_DEPS" || fail "Repo could not be found"
     cd "$BAZEL_DEPS"
-    git checkout "$BAZEL_DEPS_COMMIT" || fail "Commit could not be found"
+    git checkout "$BAZEL_DEPS_TAG" || fail "Tag could not be found"
 fi
 
 bazel run //:parse -- generate --repo-root $ROOT --deps "$ROOT/dependencies.yaml" --external 3rdparty 
